# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleDemo
   pod 'SnapKit'
  pod 'QMUIKit'
#  pod 'CocoaDebug', :configurations => ['Debug']
  pod 'SnapKit'
  pod 'SWRevealViewController'
  pod 'DoraemonKit/Core', '~> 1.2.3', :configurations => ['Debug'] 
end
